Repository celestiaorg/docs, pull requests merged in 2022-07, with the labels that each got.

#141 Update Node API `data_available`
  docs/developers/node-api.md
Labels: documentation

#158 Added Light Node video tutorial and embed CSS
  docs/developers/light-node-video.md
  docs/developers/node-tutorial.md
  docs/nodes/light-node.md
  sidebars.js
  src/css/custom.css
Labels: enhancement

#172 Prefer full command name in documentation
  docs/developers/wallet.md
Labels: enhancement

#171 fix: type of node on consensus full node steps
  docs/nodes/consensus-full-node.md
Labels: bug
