Repository celestiaorg/docs, pull requests merged in 2022-05, with the labels that each got.

#50 Community Resources and CoC
  docs/community/calendar.md
  docs/community/coc.md
  docs/community/overview.md
  docusaurus.config.js
  sidebars.js
Labels: documentation

#54 doc: fix typo
  docs/nodes/bridge-validator-node.md
Labels: bug

#67 Add mdlint
  .github/workflows/lint.yml
  docs/community/calendar.md
  docs/community/coc.md
  docs/community/overview.md
  docs/developers/node-api.md
  docs/developers/overview.md
  docs/nodes/bridge-validator-node.md
  docs/nodes/devops-resources.md
  docs/nodes/light-node.md
  docs/nodes/overview.md
  package-lock.json
  package.json
Labels: enhancement

#66 Update Node API endpoint
  docs/developers/node-api.md
Labels: documentation

#51 Add Language Support
  docusaurus.config.js
  i18n/en/code.json
  i18n/en/docusaurus-plugin-content-blog/options.json
  i18n/en/docusaurus-plugin-content-docs/current.json
  i18n/en/docusaurus-theme-classic/footer.json
  i18n/en/docusaurus-theme-classic/navbar.json
Labels: enhancement

#74 Upgrade Docusaurus
  package-lock.json
  package.json
Labels: dependencies

#71 Add Testnet Instantiation Guide
  docs/developers/instantiate-testnet.md
  sidebars.js
Labels: documentation

#78 "Run A Node" Rearchitecture
  docs/developers/node-api.md
  docs/nodes/bridge-node.md
  docs/nodes/config-toml.md
  docs/nodes/devnet-2.md
  docs/nodes/light-node.md
  docs/nodes/overview.md
  docs/nodes/validator-node.md
  sidebars.js
Labels: documentation

#89 Rearchitect Developer Section
  docs/developers/celestia-app.md
  docs/developers/celestia-node.md
  docs/developers/environment.md
  docs/developers/wallet.md
  sidebars.js
Labels: documentation

#87 Add Full Node Tutorial
  docs/nodes/devnet-2.md
  docs/nodes/full-node.md
  docs/nodes/overview.md
  sidebars.js
Labels: documentation

#88 Edits to Bridge and Validator Node Guides
  docs/nodes/bridge-node.md
  docs/nodes/light-node.md
  docs/nodes/validator-node.md
Labels: documentation

#90 Update Node API Reference
  docs/developers/node-api.md
Labels: documentation

#68 Node Tutorial Guide
  docs/developers/node-tutorial.md
  sidebars.js
Labels: documentation

#84 Update Network
  docs/nodes/bridge-node.md
  docs/nodes/light-node.md
  docs/nodes/mamaki.md
  docs/nodes/validator-node.md
  sidebars.js
  static/img/mamaki.jpg
Labels: documentation

#98 fix: resolve to correct links
  docs/nodes/bridge-node.md
  docs/nodes/validator-node.md
Labels: bug

#102 corrected sed commands
  docs/nodes/mamaki-testnet.md
Labels: bug, documentation

#107 docs: Update cover image
  docs/nodes/mamaki-testnet.md
  static/img/mamaki.jpg
  static/img/mamaki.png
Labels: documentation

#114 Add Another RPC Endpoint
  docs/nodes/mamaki-testnet.md
Labels: documentation

#109 Bump celestia-node version
  docs/developers/celestia-node.md
Labels: documentation

#115 Doc Cleanups and Adding Full Storage Node and Consensus Full Nodes
  docs/developers/environment.md
  docs/nodes/bridge-node.md
  docs/nodes/consensus-full-node.md
  docs/nodes/full-node.md
  docs/nodes/full-storage-node.md
  docs/nodes/keys.md
  docs/nodes/light-node.md
  docs/nodes/mamaki-testnet.md
  docs/nodes/overview.md
  docs/nodes/systemd.md
  docs/nodes/validator-node.md
  sidebars.js
Labels: documentation

#125 Update node-tutorial.md
  docs/developers/node-tutorial.md
Labels: documentation

#126 Fix Broken Edit Link
  docusaurus.config.js
Labels: bug

#128 fix: broken link
  docs/nodes/light-node.md
Labels: bug
