Repository celestiaorg/docs, pull requests merged in 2022-06, with the labels that each got.

#127 Add http prefix
  docs/developers/node-tutorial.md
  docs/nodes/bridge-node.md
  docs/nodes/full-storage-node.md
  docs/nodes/light-node.md
  docs/nodes/systemd.md
  docs/nodes/validator-node.md
Labels: documentation

#130 More Link Fixes
  docs/developers/celestia-app.md
  docs/developers/celestia-node.md
  docs/developers/node-tutorial.md
  docs/nodes/bridge-node.md
  docs/nodes/consensus-full-node.md
  docs/nodes/full-storage-node.md
  docs/nodes/light-node.md
  docs/nodes/mamaki-testnet.md
  docs/nodes/overview.md
  docs/nodes/validator-node.md
Labels: bug

#136 Add `head` Endpoint and Make Code-Blocks Scrollable
  docs/developers/node-api.md
  src/css/custom.css
Labels: documentation, enhancement

#138 Add Algolia Search Bar
  docusaurus.config.js
Labels: enhancement

#143 Add minor doc fixes
  docs/developers/instantiate-testnet.md
  docs/developers/node-tutorial.md
Labels: documentation

#144 Update mamaki-testnet.md
  docs/nodes/mamaki-testnet.md
Labels: documentation

#148 Update API key
  docusaurus.config.js
Labels: bug
