Repository celestiaorg/docs, pull requests merged in 2022-08, with the labels that each got.

#173 Added setup instructions to main documentation for light node tutorials
  docs/developers/environment.md
  docs/developers/node-tutorial.md
  docs/nodes/light-node.md
Labels: documentation, enhancement

#174 Update twitter card image
  docusaurus.config.js
  static/img/celestia-doc.png
Labels: enhancement

#147 Wordle with Optimint
  docs/developers/install-optimint.md
  docs/developers/run-wordle.md
  docs/developers/scaffold-wordle.md
  docs/developers/wordle-keeper.md
  docs/developers/wordle-messages.md
  docs/developers/wordle-module.md
  docs/developers/wordle-types.md
  docs/developers/wordle.md
  sidebars.js
  static/img/wordle.jpg
Labels: documentation

#151 Add Cosmwasm Optimint Tutorial
  docs/developers/cosmwasm-contract-deployment.md
  docs/developers/cosmwasm-contract-interaction.md
  docs/developers/cosmwasm-dependency.md
  docs/developers/cosmwasm-environment.md
  docs/developers/cosmwasm.md
  sidebars.js
Labels: documentation

#176 Update optimint disclaimer
  docs/developers/cosmwasm.md
  docs/developers/wordle.md
Labels: documentation

#177 Add new twitter card img
  static/img/celestia-doc.png
Labels: enhancement

#178 Update twitter card info
  docusaurus.config.js
Labels: enhancement

#165 Added modular fellows program
  docs/community/modular-fellows.md
  sidebars.js
  static/img/modular_fellows.jpg
Labels: enhancement

#180 fix: remove trailing head tag
  src/pages/index.js
Labels: bug

#181 Add CosmWasm Resources
  docs/developers/cosmwasm-resources.md
  sidebars.js
Labels: documentation

#205 Remove link to unmaintained celestia-core branch
  docs/concepts/how-celestia-works/data-availability-layer.md
Labels: documentation
