Repository celestiaorg/docs, pull requests merged in 2022-10, with the labels that each got.

#240 Add Mamaki Section to Light Node
  docs/nodes/light-node.md
Labels: documentation

#247 Add more celestia-app commands
  docs/developers/celestia-app-commands.md
Labels: documentation

#246 Add node network selection
  docs/developers/celestia-node.md
Labels: documentation

#245 Add Celestia Node Metrics section
  docs/developers/celestia-node-metrics.md
  i18n/fr/docusaurus-plugin-content-docs/current/developers/celestia-node-metrics.md
  i18n/zh/docusaurus-plugin-content-docs/current/developers/celestia-node-metrics.md
  sidebars.js
Labels: documentation

#258 doc: increase gas from 60k to 70k in pfd example
  docs/developers/node-tutorial.md
Labels: documentation

#269 Truncate head response
  docs/developers/node-api.md
Labels: bug

#275 Add GH-Preview Workflow
  .env
  .github/workflows/preview.yml
  docusaurus.config.js
  package.json
  yarn.lock
Labels: enhancement

#274 Add DS_STORE to gitignore
  .gitignore
Labels: enhancement

#281 Version bump to v0.4.2
  docs/developers/celestia-node.mdx
  docs/developers/node-tutorial.mdx
  docs/nodes/light-node.mdx
Labels: documentation

#282 Resolve Crowdin CI issue
  crowdin.yml
Labels: bug

#283 Bump docusaurus version
  package.json
  yarn.lock
Labels: dependencies
