Repository celestiaorg/docs, pull requests merged in 2022-11, with the labels that each got.

#289 Add sidebar_label
  docs/concepts/how-celestia-works/data-availability-layer.md
  docs/concepts/how-celestia-works/introduction.md
  docs/concepts/how-celestia-works/monolithic-vs-modular.md
  docs/concepts/how-celestia-works/transaction-lifecycle.md
  docs/concepts/specifications/reserved-namespace-id.md
  docs/developers/celestia-node-metrics.md
  docs/developers/rollmint.md
Labels: documentation

#288 Cleanup script for Crowdin and Update Crowdin
  .github/scripts/clean.sh
  .github/workflows/deploy.yml
  yarn.lock
Labels: bug

#290 Add eslint for MDX
  .eslintrc.json
  .github/workflows/lint.yml
  docs/developers/node-tutorial.mdx
  docs/nodes/light-node.mdx
  package.json
  yarn.lock
Labels: enhancement

#293 Update translation guides for managers
  docs/community/translations.md
Labels: documentation

#291 fix: Resolve workflow issue
  .github/workflows/deploy.yml
Labels: bug

#276 Add hardfork process doc
  docs/nodes/hardfork-process.md
  sidebars.js
Labels: documentation

#294 Cleanup script fix
  .github/workflows/deploy.yml
  .github/workflows/test-deploy.yml
  clean.sh
Labels: bug

#295 Remove useful information for HF Process
  docs/nodes/hardfork-process.md
Labels: documentation

#298 remove duplicate commands
  docs/developers/node-tutorial.mdx
Labels: documentation

#287 update macOS installation instructions for `celestia-node`
  docs/developers/celestia-node.mdx
  docs/developers/node-tutorial.mdx
  docs/nodes/light-node.mdx
Labels: bug, enhancement

#309 Update NMT diagram
  static/img/concepts/nmt.png
Labels: documentation

#314 Update cli command in systemd light node
  docs/nodes/systemd.md
Labels: documentation

#272 Celestia Node v0.5.0
  docs/developers/celestia-node-metrics.md
  docs/developers/celestia-node.mdx
  docs/developers/node-tutorial.mdx
  docs/nodes/light-node.mdx
Labels: documentation, unreleased-node

#315 Docs Rearchitecture Part 1
  docs/developers/celestia-app-wallet.md
  docs/developers/celestia-node-key.md
  docs/developers/cosmwasm-dependency.md
  docs/developers/cosmwasm-environment.md
  docs/developers/gm-setup.mdx
  docs/developers/overview.md
  docs/developers/recipe-book.mdx
  docs/developers/run-wordle.md
  docs/nodes/bridge-node.md
  docs/nodes/celestia-app-commands.md
  docs/nodes/celestia-app.mdx
  docs/nodes/celestia-node-metrics.md
  docs/nodes/celestia-node.mdx
  docs/nodes/consensus-full-node.md
  docs/nodes/decide-node.md
  docs/nodes/docker.mdx
  docs/nodes/environment.mdx
  docs/nodes/full-storage-node.md
  docs/nodes/instantiate-testnet.md
  docs/nodes/light-node.mdx
  docs/nodes/mamaki-testnet.md
  docs/nodes/quick-start.md
  docs/nodes/validator-node.md
  docusaurus.config.js
  package.json
  sidebars.js
  src/css/custom.css
  yarn.lock
Labels: documentation

#292 Chinese, Russian and Spanish Language Support
  crowdin.yml
  docusaurus.config.js
Labels: enhancement

#326 Build Modular doc
  docs/developers/build-modular.md
  sidebars.js
  static/img/shared-execution.png
Labels: documentation

#327 Fix: Remove zh due to encoding bugs, update cleanup script
  clean.sh
  crowdin.yml
  docusaurus.config.js
Labels: bug

#328 fix: Remove ru, update test-deploy to build all
  .github/workflows/test-deploy.yml
  crowdin.yml
  docusaurus.config.js
Labels: bug

#329 fix: Remove ES
  crowdin.yml
  docusaurus.config.js
Labels: bug

#330 Crowdin Specify Download of Only Approved Translations
  crowdin.yml
  package.json
Labels: bug

#332 fix: Resolve markdown issue by adding mdx-code-block
  docs/developers/celestia-node-key.mdx
  docs/developers/gm-query.md
  docs/developers/gm-setup.md
  docs/developers/gm-world.md
  docs/developers/keplr.mdx
  docs/developers/node-tutorial.mdx
  docs/developers/recipe-book.md
  docs/developers/recipe-book.mdx
  docs/developers/recipe-keeper.md
  docs/developers/recipe-keeper.mdx
  docs/developers/recipe-message.md
  docs/developers/recipe-query.md
  docs/developers/recipe-rollup.md
  docs/developers/recipe-scaffold.md
  docs/developers/rollmint.md
  docs/nodes/bridge-node.mdx
  docs/nodes/celestia-app.mdx
  docs/nodes/celestia-node.mdx
  docs/nodes/docker-images.mdx
  docs/nodes/environment.mdx
  docs/nodes/full-storage-node.mdx
  docs/nodes/light-node.mdx
  package.json
Labels: bug

#333 feat: remove fr for debugging
  docusaurus.config.js
Labels: bug

#325 New Rollmint Updates
  docs/developers/cosmwasm-environment.md
  docs/developers/gm-query.md
  docs/developers/gm-rollmint.md
  docs/developers/recipe-rollup.md
  docs/developers/run-wordle.md
  docs/developers/wordle-node.md
  sidebars.js
Labels: documentation
