Repository celestiaorg/docs, pull requests merged in 2023-09, with the labels that each got.

#962 docs: add staking page
  docs/developers/staking.md
  sidebars.js
Labels: documentation, enhancement

#1066 fix: remove reserved namespaces table
  docs/learn/specifications/reserved-namespaces.md
  docusaurus.config.js
  sidebars.js
Labels: bug, documentation

#1063 fix: resolve gas -> utia #1062
  docs/developers/node-tutorial.mdx
Labels: bug, documentation

#1074 Update Deploy with force_orphan as true
  .github/workflows/deploy.yml
Labels: enhancement
