Repository celestiaorg/docs, pull requests merged in 2023-05, with the labels that each got.

#703 Collapse BSR endpoints to reduce clutter and fix broken links
  docs/nodes/blockspace-race.mdx
Labels: bug, documentation, enhancement

#707 docs: Phase 5
  docs/nodes/blockspace-race.mdx
  docs/nodes/itn-hardfork-upgrade.md
  docs/nodes/itn-qgb-setup.md
  docs/nodes/itn-upgrade-node-bridge.md
  docs/nodes/itn-upgrade-node-light-full.md
  static/img/phase5.jpg
Labels: documentation

#708 Update validator-node.md
  docs/nodes/validator-node.md
Labels: documentation

#690 add OP x Celestia doc
  docs/developers/optimism.md
  sidebars.js
Labels: documentation, enhancement

#719 Modular Meetups
  docs/community/modular-meetup-guide.md
  docs/community/modular-meetup-intro.md
  docs/community/modular-meetup-toolkit.md
  docs/community/speaker-list.md
  sidebars.js
  static/img/Celestia_Modular_meetup2.jpg
Labels: documentation
