Repository celestiaorg/docs, pull requests merged in 2023-04, with the labels that each got.

#614 docs: add info on troubleshooting & keys for ITN docs
  docs/concepts/how-celestia-works/data-availability-layer.md
  docs/concepts/how-celestia-works/transaction-lifecycle.md
  docs/developers/celestia-app-wallet.md
  docs/developers/celestia-node-key.mdx
  docs/developers/integrate-celestia.md
  docs/developers/node-gateway-docs.mdx
  docs/developers/node-tutorial.mdx
  docs/nodes/arabica-devnet.md
  docs/nodes/blockspace-race.md
  docs/nodes/bridge-node.mdx
  docs/nodes/celestia-app.mdx
  docs/nodes/celestia-node-metrics.md
  docs/nodes/celestia-node.mdx
  docs/nodes/config-toml.md
  docs/nodes/consensus-full-node.md
  docs/nodes/environment.mdx
  docs/nodes/full-storage-node.mdx
  docs/nodes/instantiate-testnet.md
  docs/nodes/itn-deploy-bridge.md
  docs/nodes/itn-deploy-full.md
  docs/nodes/itn-deploy-light.md
  docs/nodes/itn-enable-telemetry-nodes.md
  docs/nodes/itn-high-uptime-node.md
  docs/nodes/itn-rpc-node.md
  docs/nodes/itn-setup-validator.md
  docs/nodes/itn-toolings.md
  docs/nodes/light-node.mdx
  docs/nodes/mocha-testnet.md
  docs/nodes/overview.md
  docs/nodes/quick-start.md
  docs/nodes/systemd.md
  docs/nodes/validator-node.md
  sidebars.js
Labels: documentation

#616 docs: add variables for BSR versions on BSR page
  docs/nodes/blockspace-race.mdx
  docs/nodes/itn-rpc-node.md
  docs/nodes/participate.md
  src/components/VersionTags.jsx
  versions/constants.js
Labels: documentation, enhancement

#572 Update tx-lifecycle diagram
  static/img/concepts/tx-lifecycle.png
Labels: documentation

#623 docs: add section on docker persistent storage
  docs/nodes/docker-images.mdx
Labels: documentation, enhancement

#633 docs: update link and comment out broken link
  docs/community/cohort-one-content.md
Labels: documentation

#625 docs: add more to rpc cli guide
  docs/developers/rpc-tutorial.mdx
Labels: documentation, enhancement

#637 docs: add section on node store location & keys
  docs/nodes/celestia-node.mdx
Labels: documentation, enhancement

#646 chore: reword the qgb setup keys to refer to only one key
  docs/nodes/validator-node.md
Labels: documentation

#657 add unsafe-reset-store docs for v0.9.0 and higher
  docs/nodes/celestia-node.mdx
Labels: documentation, enhancement, dependencies

#659 feat: remove locale select in navbar
  docusaurus.config.js
Labels: enhancement

#663 docs: update instructions for config remove + add tabs for these sections
  docs/nodes/celestia-node.mdx
Labels: documentation, enhancement

#658 Add variable for golang on bsr
  docs/developers/node-tutorial.mdx
  docs/developers/prompt-scavenger.mdx
  docs/nodes/celestia-node.mdx
  docs/nodes/light-node.mdx
  versions/constants.js
Labels: documentation, dependencies

#643 style: add sentence case
  docs/developers/node-tutorial.mdx
Labels: documentation, enhancement, dependencies

#665 fix: missing variables from #658
  docs/developers/prompt-scavenger.mdx
  docs/nodes/environment.mdx
Labels: bug, documentation, dependencies

#671 docs: remove devops-resources and local-devnet
  docs/nodes/devops-resources.md
  docs/nodes/local-devnet.mdx
  sidebars.js
Labels: documentation, enhancement

#675 docs: troubleshooting section for headers
  docs/nodes/celestia-node.mdx
Labels: documentation

#685 Add phase 4
  docs/nodes/blockspace-race.mdx
  docs/nodes/itn-address-mainnet.md
  docs/nodes/itn-vote-governance.md
  static/img/phase4.jpg
Labels: documentation

#688 fix: typo
  docs/nodes/itn-vote-governance.md
Labels: documentation

#668 Add QGB docs
  docs/nodes/ibc-relayer.md
  docs/nodes/qgb-binary.mdx
  docs/nodes/qgb-deploy.md
  docs/nodes/qgb-intro.md
  docs/nodes/qgb-keys.md
  docs/nodes/qgb-orchestrator.md
  docs/nodes/qgb-relayer.md
  importMarkdown.mjs
  package-lock.json
  package.json
  sidebars.js
  src/components/InlineText.js
  src/components/RemoteMarkdown.js
  src/css/custom.css
  static/img/qgb/qgb-diagram.png
  static/img/qgb/qgb-orchestrator.png
  static/img/qgb/qgb-relayer.png
  versions/constants.js
  yarn.lock
Labels: documentation, enhancement
