Repository celestiaorg/docs, pull requests merged in 2023-03, with the labels that each got.

#496 deps: upgrade arabica versions
  versions/arabica_versions.js
Labels: documentation, dependencies

#512 docs: Add geo guide
  docs/nodes/itn-setup-validator.md
Labels: documentation

#551 Update commands to reinit nodes
  docs/nodes/celestia-node.mdx
Labels: documentation

#565 fix: wrong network in docker command
  docs/nodes/docker-images.mdx
Labels: documentation

#562 Prompt Scavenger
  docs/developers/prompt-scavenger.md
  sidebars.js
Labels: documentation

#568 Add faucet section for BSR
  docs/nodes/blockspace-race.md
Labels: documentation

#569 Add project repos to MF calendar/content
  docs/community/cohort-one-content.md
Labels: documentation, enhancement

#549 Remove fuelmint tutorial
  docs/developers/fuelmint.md
  sidebars.js
Labels: documentation

#561 ITN P2
  docs/nodes/blockspace-race.md
  docs/nodes/itn-claim-rewards.md
  docs/nodes/itn-deploy-bridge.md
  docs/nodes/itn-deploy-full.md
  docs/nodes/itn-deploy-light.md
  docs/nodes/itn-deploy-rollup.md
  docs/nodes/itn-enable-telemetry-nodes.md
  docs/nodes/itn-high-uptime-node.md
  docs/nodes/itn-node-analysis.md
  docs/nodes/itn-pfb-ui.md
  docs/nodes/itn-rpc-node.md
  docs/nodes/itn-setup-writeup.md
  docs/nodes/itn-toolings.md
  static/img/phase2.jpg
Labels: documentation

#574 Add port section
  docs/developers/celestia-app-wallet.md
  docs/developers/celestia-node-key.mdx
  docs/developers/node-tutorial.mdx
  docs/developers/prompt-scavenger.mdx
  docs/developers/rpc-tutorial.mdx
  docs/nodes/bridge-node.mdx
  docs/nodes/celestia-node-metrics.md
  docs/nodes/celestia-node.mdx
  docs/nodes/consensus-full-node.md
  docs/nodes/docker-images.mdx
  docs/nodes/full-storage-node.mdx
  docs/nodes/instantiate-testnet.md
  docs/nodes/light-node.mdx
  docs/nodes/validator-node.md
Labels: documentation, enhancement

#579 fix: pfd -> pfb for mocha
  docs/nodes/full-storage-node.mdx
  docs/nodes/light-node.mdx
Labels: documentation

#584 docs: add callouts for clearing data store
  docs/nodes/celestia-node.mdx
Labels: documentation

#587 docs: put docker first
  sidebars.js
Labels: enhancement

#590 Add links to pfb/retrieve data to ITN task
  docs/nodes/itn-pfb-ui.md
Labels: documentation

#601 chore: remove /transfer endpoint & add BSR tab for PFB
  docs/developers/node-gateway-docs.mdx
Labels: documentation

#594 Add link to docker key management section
  docs/nodes/docker-images.mdx
Labels: documentation, enhancement

#602 Add more details for ports on node/app
  docs/nodes/celestia-app.mdx
  docs/nodes/celestia-node.mdx
Labels: documentation, enhancement

#604 Add CLI docs
  docs/developers/rpc-tutorial.mdx
  docusaurus.config.js
Labels: documentation, enhancement

#607 Add upgrade your binary section
  docs/nodes/celestia-node.mdx
Labels: documentation, enhancement
