Repository celestiaorg/docs, pull requests merged in 2023-02, with the labels that each got.

#433 Add construction sign (Arabica) and rearrange Mocha & Arabica
  docs/developers/keplr.mdx
  docs/developers/node-tutorial.mdx
  docs/nodes/bridge-node.mdx
  docs/nodes/celestia-app.mdx
  docs/nodes/celestia-node-metrics.md
  docs/nodes/celestia-node.mdx
  docs/nodes/docker-images.mdx
  docs/nodes/environment.mdx
  docs/nodes/full-storage-node.mdx
  docs/nodes/light-node.mdx
  docs/nodes/systemd.md
  docs/nodes/validator-node.md
Labels: documentation, enhancement

#437 Update node endpoints with `fees` parameter
  docs/developers/node-api.md
Labels: documentation, dependencies

#441 deps: version bump to 0.6.3 for mocha
  docs/developers/node-tutorial.mdx
  docs/nodes/celestia-node.mdx
  docs/nodes/docker-images.mdx
  docs/nodes/light-node.mdx
Labels: documentation, dependencies

#446 change install rollkit commands (temporary)
  docs/developers/cosmwasm-dependency.md
  docs/developers/gm-rollmint.md
  docs/developers/install-rollmint.md
  docs/developers/recipe-scaffold.md
  docs/developers/rollmint-on-ethermint.md
Labels: bug, documentation, dependencies

#442 deps: version bump to 0.6.4 for Mocha
  docs/developers/node-tutorial.mdx
  docs/nodes/celestia-node.mdx
  docs/nodes/docker-images.mdx
  docs/nodes/light-node.mdx
Labels: documentation, dependencies

#456 Upgrade Arabica to v0.7.0-rc1
  docs/developers/keplr.mdx
  docs/developers/node-tutorial.mdx
  docs/nodes/celestia-node.mdx
  docs/nodes/docker-images.mdx
  docs/nodes/light-node.mdx
Labels: documentation, dependencies, unreleased-node

#443 Add Demo Day link to Community section
  docs/community/cohort-one-content.md
Labels: documentation

#444 Add Full Storage, Consensus, and Consensus Full Node diagrams
  docs/nodes/bridge-node.mdx
  docs/nodes/consensus-full-node.md
  docs/nodes/full-storage-node.mdx
  docs/nodes/validator-node.md
  static/img/full-storage-node.png
  static/img/nodes/consensus-full-node.png
  static/img/nodes/validator.png
Labels: documentation

#451 Remove incorrect command from celestia-node wallet page
  docs/developers/celestia-node-key.mdx
Labels: bug, documentation

#465 Update docker image for mocha with sha, until release is tagged
  docs/nodes/docker-images.mdx
Labels: bug, documentation

#452 Add guide on `local-celestia-devnet`
  docs/nodes/local-devnet.md
  sidebars.js
Labels: documentation, enhancement

#453 doc: add guide on managing wallets in docker
  docs/developers/celestia-node-key.mdx
Labels: documentation, unreleased-node

#469 Add new `Celestia - Docs` logo
  docusaurus.config.js
  static/img/celestia-docs-dark.svg
  static/img/celestia-docs.svg
Labels: documentation, enhancement

#473 deps: bump arabica version & chain id
  versions/arabica_versions.js
  versions/constants.js
Labels: documentation, dependencies

#474 deps: remove slice on arabica docker images
  docs/nodes/docker-images.mdx
Labels: documentation, dependencies

#475 bump node version for arabica
  versions/arabica_versions.js
Labels: documentation, dependencies

#478 change Celestia blocktime to 15s
  docs/developers/integrate-celestia.md
Labels: documentation

#472 Remove rollmint & swap for rollkit
  docs/community/cohort-one-content.md
  docs/developers/build-modular.md
  docs/developers/cosmwasm-contract-deployment.mdx
  docs/developers/cosmwasm-contract-interaction.md
  docs/developers/cosmwasm-dependency.md
  docs/developers/cosmwasm-environment.md
  docs/developers/cosmwasm-resources.md
  docs/developers/cosmwasm.md
  docs/developers/deploy-solidity-ethermint-foundry.md
  docs/developers/ethermint-dependencies.md
  docs/developers/ethermint.md
  docs/developers/full-stack-modular-development-guide.md
  docs/developers/gm-next.md
  docs/developers/gm-node.md
  docs/developers/gm-query.md
  docs/developers/gm-rollmint.md
  docs/developers/gm-setup.md
  docs/developers/gm-world.md
  docs/developers/install-rollmint.md
  docs/developers/instantiate-ethermint.md
  docs/developers/overview.md
  docs/developers/recipe-book.md
  docs/developers/recipe-keeper.md
  docs/developers/recipe-message.md
  docs/developers/recipe-query.md
  docs/developers/recipe-rollup.md
  docs/developers/recipe-scaffold.md
  docs/developers/rollkit.md
  docs/developers/rollmint-on-ethermint.md
  docs/developers/rollmint.md
  docs/developers/run-wordle.md
  docs/developers/scaffold-wordle.md
  docs/developers/wordle-keeper.md
  docs/developers/wordle-messages.md
  docs/developers/wordle-module.md
  docs/developers/wordle-node.md
  docs/developers/wordle-types.md
  docs/developers/wordle.md
  sidebars.js
  src/pages/index.js
  static/img/gm/1.png
  static/img/gm/2.png
  static/img/gm/3.png
  static/img/gm/4.png
  static/img/recipes/light-node.png
  static/img/recipes/query.gif
  static/img/recipes/query.png
  static/img/recipes/recipe-start.gif
  static/img/recipes/send-tx.png
  static/img/rollkit.png
  static/img/rollmint.png
  static/img/wordle.jpg
Labels: documentation, unreleased-rollmint

#481 Update hardware requirements
  docs/nodes/bridge-node.mdx
  docs/nodes/validator-node.md
Labels: documentation, dependencies

#485 Add HQ favicon 48x48px
  static/img/favicon.ico
Labels: documentation, enhancement

#479 Converting docs to sentence case
  docs/community/calendar.md
  docs/community/cohort-one-content.md
  docs/community/overview.md
  docs/community/translations.md
  docs/concepts/data-availability-faq.md
  docs/concepts/how-celestia-works/data-availability-layer.md
  docs/concepts/how-celestia-works/monolithic-vs-modular.md
  docs/concepts/how-celestia-works/transaction-lifecycle.md
  docs/developers/build-modular.md
  docs/developers/celestia-app-wallet.md
  docs/developers/celestia-node-key.mdx
  docs/developers/full-stack-modular-development-guide.md
  docs/developers/integrate-celestia.md
  docs/developers/keplr.mdx
  docs/developers/light-node-video.md
  docs/developers/node-api.md
  docs/developers/node-tutorial.mdx
  docs/developers/overview.md
  docs/developers/rollkit.md
  docs/nodes/arabica-devnet.md
  docs/nodes/bridge-node.mdx
  docs/nodes/celestia-app-commands.md
  docs/nodes/celestia-app.mdx
  docs/nodes/celestia-node-metrics.md
  docs/nodes/celestia-node.mdx
  docs/nodes/config-toml.md
  docs/nodes/consensus-full-node.md
  docs/nodes/decide-node.md
  docs/nodes/devops-resources.md
  docs/nodes/docker-images.mdx
  docs/nodes/environment.mdx
  docs/nodes/full-storage-node.mdx
  docs/nodes/hardfork-process.md
  docs/nodes/instantiate-testnet.md
  docs/nodes/light-node.mdx
  docs/nodes/local-devnet.md
  docs/nodes/mocha-testnet.md
  docs/nodes/participate.md
  docs/nodes/quick-start.md
  docs/nodes/systemd.md
  docs/nodes/validator-node.md
  sidebars.js
  src/pages/index.js
Labels: documentation, enhancement

#471 Fuelmint docs
  docs/developers/fuelmint.md
  sidebars.js
Labels: documentation, enhancement

#493 Add initial landing page
  docs/nodes/blockspace-race.md
  sidebars.js
  static/img/blockspace_race.jpg
Labels: documentation
