Repository celestiaorg/docs, pull requests merged in 2023-01, with the labels that each got.

#408 update: fix p2p network label for 0.6.1 arabica
  docs/developers/celestia-node-key.mdx
  docs/developers/node-tutorial.mdx
  docs/nodes/bridge-node.mdx
  docs/nodes/full-storage-node.mdx
  docs/nodes/light-node.mdx
Labels: documentation

#409 Add revised Light Node diagram
  static/img/nodes/LightNodes.png
Labels: documentation

#403 docs: change instructions from Arabica to Mocha on cosmwasm dependenc…
  docs/developers/cosmwasm-dependency.md
Labels: documentation, dependencies

#305 Update RPC/gRPC/API Endpoints and Descriptions
  docs/nodes/arabica-devnet.md
  docs/nodes/mocha-testnet.md
Labels: documentation

#381 docs: v0.6.2 updates
  docs/developers/node-api.md
  docs/developers/node-tutorial.mdx
  docs/nodes/celestia-node.mdx
  docs/nodes/docker-images.mdx
  docs/nodes/light-node.mdx
Labels: documentation, unreleased-node

#426 Add trailing slash to all internal links
  README.md
  docs/community/cohort-one-content.md
  docs/community/itn-tos.md
  docs/community/modular-fellows.md
  docs/concepts/data-availability-faq.md
  docs/concepts/how-celestia-works/data-availability-layer.md
  docs/concepts/how-celestia-works/introduction.md
  docs/concepts/how-celestia-works/transaction-lifecycle.md
  docs/developers/build-modular.md
  docs/developers/celestia-node-key.mdx
  docs/developers/cosmwasm-contract-deployment.mdx
  docs/developers/cosmwasm-dependency.md
  docs/developers/cosmwasm-resources.md
  docs/developers/cosmwasm.md
  docs/developers/deploy-solidity-ethermint-foundry.md
  docs/developers/ethermint.md
  docs/developers/full-stack-modular-development-guide.md
  docs/developers/gm-rollmint.md
  docs/developers/gm-setup.md
  docs/developers/gm-world.md
  docs/developers/integrate-celestia.md
  docs/developers/keplr.mdx
  docs/developers/node-tutorial.mdx
  docs/developers/recipe-book.md
  docs/developers/rollmint.md
  docs/developers/scaffold-wordle.md
  docs/developers/wordle-module.md
  docs/developers/wordle.md
  docs/nodes/arabica-devnet.md
  docs/nodes/bridge-node.mdx
  docs/nodes/celestia-node-metrics.md
  docs/nodes/consensus-full-node.md
  docs/nodes/docker-images.mdx
  docs/nodes/environment.mdx
  docs/nodes/full-storage-node.mdx
  docs/nodes/hardfork-process.md
  docs/nodes/light-node.mdx
  docs/nodes/mocha-testnet.md
  docs/nodes/participate.md
  docs/nodes/quick-start.md
  docs/nodes/validator-node.md
  docusaurus.config.js
Labels: bug, documentation

#423 Set `keep_files: true` on `preview.yml`
  .github/workflows/preview.yml
Labels: documentation

#434 Update arabica API endpoint
  docs/nodes/arabica-devnet.md
Labels: documentation
