Repository celestiaorg/docs, pull requests merged in 2023-10, with the labels that each got.

#1096 chore: update node requirements
  docs/img/node-requirements.jpg
  docs/nodes/bridge-node.mdx
  docs/nodes/full-storage-node.mdx
  docs/nodes/light-node.mdx
Labels: documentation

#1095 chore: resolve inaccuracies around exposing consensus node's RPC
  docs/nodes/full-consensus-node.mdx
Labels: documentation, enhancement

#1085 Rollups overview page
  docs/developers/overview.md
  docs/developers/rollup-overview.md
  sidebars.js
  src/pages/index.js
Labels: documentation, enhancement

#1107 chore: consolidate consensus nodes into one page
  docs/developers/celestia-app-vesting.md
  docs/nodes/arabica-devnet.mdx
  docs/nodes/consensus-node.mdx
  docs/nodes/decide-node.md
  docs/nodes/full-consensus-node.mdx
  docs/nodes/instantiate-testnet.md
  docs/nodes/mocha-testnet.mdx
  docs/nodes/overview.md
  docs/nodes/qgb-intro.md
  docs/nodes/qgb-orchestrator.md
  docs/nodes/systemd.md
  docusaurus.config.js
  sidebars.js
  src/components/PeersLink.js
  src/components/SeedsLink.js
  src/pages/arabica-9.mdx
Labels: documentation, enhancement

#1110 fix: missed "no click heres"
  README.md
  docs/nodes/full-storage-node.mdx
Labels: documentation

#1125 chore: remove custom api component/pages, use node-rpc-docs.celestia.org
  README.md
  docs/developers/node-api.md
  docs/developers/node-tutorial.mdx
  docs/developers/overview.md
  docs/developers/submit-data.md
  sidebars.js
  src/components/ApiComponent.jsx
  src/components/ApiComponent.module.css
  src/components/CustomVersionSelector.css
  src/components/CustomVersionSelector.jsx
  src/openrpc-spec/openrpc-v0.11.0-rc11.json
  src/openrpc-spec/openrpc-v0.11.0-rc12.json
  src/openrpc-spec/openrpc-v0.11.0-rc13.json
  src/openrpc-spec/openrpc-v0.11.0-rc8-arabica-improvements.json
  src/openrpc-spec/openrpc-v0.11.0-rc8.json
  src/pages/api/v0.11.0-rc11.js
  src/pages/api/v0.11.0-rc12.js
  src/pages/api/v0.11.0-rc13.js
  src/pages/api/v0.11.0-rc8-arabica-improvements.js
  src/pages/api/v0.11.0-rc8.js
  src/theme/Layout/index.js
  src/theme/Navbar/Content/index.js
  src/theme/Navbar/MobileSidebar/PrimaryMenu/index.js
Labels: documentation

#1129 chore: Core/App Doc Updates
  docs/nodes/consensus-node.mdx
  docs/nodes/instantiate-testnet.md
Labels: documentation

#1128 chore: Node Docs Updates
  docs/nodes/celestia-node-custom-networks.md
  docs/nodes/celestia-node-metrics.md
  sidebars.js
Labels: documentation, enhancement

#1127 chore: update rpc tutorial for new version
  docs/developers/node-tutorial.mdx
  src/components/InlineTextCode.js
Labels: documentation, unreleased-node

#1131 chore: fix typo
  docs/developers/node-tutorial.mdx
Labels: documentation

#1141 docs: update instantiate testnet and bridge node
  docs/nodes/bridge-node.mdx
  docs/nodes/instantiate-testnet.md
Labels: documentation

#1149 chore: add missing --p2p.network flags
  docs/developers/node-tutorial.mdx
  docs/nodes/light-node.mdx
Labels: documentation

#1115 chore: change instances of "qgb" to "Blobstream", update workflow
  docs/community/cohort-one-content.md
  docs/constants/constants.js
  docs/img/blobstream/Blobstream.png
  docs/img/blobstream/blobstream-orchestrator.png
  docs/img/blobstream/blobstream-relayer.png
  docs/img/qgb/qgb-diagram.png
  docs/img/qgb/qgb-orchestrator.png
  docs/img/qgb/qgb-relayer.png
  docs/nodes/blobstream-binary.mdx
  docs/nodes/blobstream-deploy.md
  docs/nodes/blobstream-intro.md
  docs/nodes/blobstream-keys.md
  docs/nodes/blobstream-orchestrator.md
  docs/nodes/blobstream-relayer.md
  docs/nodes/blockspace-race.mdx
  docs/nodes/consensus-node.mdx
  docs/nodes/hardfork-process.md
  docs/nodes/qgb-binary.mdx
  docs/nodes/qgb-deploy.md
  docs/nodes/qgb-intro.md
  importMarkdown.mjs
  sidebars.js
Labels: documentation, unreleased-app/core

#1153 docs: update IBC guide
  docs/developers/ibc-relayer.md
  docs/nodes/ibc-relayer.md
  docusaurus.config.js
  sidebars.js
Labels: documentation, P0

#1152 Add docs for integrating Blobstream
  docs/developers/blobstream-contracts.md
  docs/developers/blobstream-offchain.md
  docs/developers/blobstream.md
  docs/developers/demos.md
  docs/developers/gm-portal-bubs.md
  docs/developers/intro-to-op-stack.md
  docs/developers/overview.md
  docs/img/blobstream/blobstream_logo.png
  docs/learn/data-availability-faq.md
  docs/nodes/blobstream-intro.md
  docs/nodes/consensus-node.mdx
  sidebars.js
Labels: enhancement

#1162 Update blobstream.md
  docs/developers/blobstream.md
Labels: documentation

#1172 fix: favicon (turn off dark mode favicon)
  .vitepress/config.ts
Labels: bug

#1174 fix: long latex equations
  developers/submit-data.md
Labels: bug

#1191 feat: add sitemap
  .vitepress/config.ts
Labels: enhancement

#1194 chore: update graphic
  public/img/node-requirements.jpg
Labels: documentation

#1198 feat: add celestia-app prebuilt binary script
  nodes/celestia-app.md
  public/celestia-app.sh
Labels: enhancement

#1205 fix: script echo
  nodes/celestia-app.md
  public/celestia-app.sh
Labels: bug

#1207 chore: add transaction resubmission document to nodes/resources section
  .vitepress/config.ts
  nodes/systemd.md
  nodes/transaction-resubmission.md
Labels: documentation

#1210 Minor fixes on blobstream docs
  developers/blobstream-offchain.md
Labels: documentation

#1212 chore: add docs on denominations
  learn/tia.md
Labels: documentation, enhancement

#1221 fix: remove mocha explorer that is set up for mainnet
  nodes/mocha-testnet.md
Labels: bug
