Repository celestiaorg/docs, pull requests merged in 2024-01, with the labels that each got.

#1316 feat: upgrade to arabica-11
  .vitepress/components/ArabicaDevnetDetails.vue
  .vitepress/components/ArabicaVersionTags.vue
  .vitepress/constants/arabica_versions.js
  .vitepress/constants/constants.js
  developers/arbitrum-mocha.md
  developers/node-tutorial.md
  nodes/arabica-devnet.md
  nodes/light-node.md
Labels: bug, documentation

#1346 feat: update OP to v1.0.0-OP_op-node/v1.4.0-CN_v0.12.1
  developers/optimism-devnet.md
Labels: documentation

#1350 feat: add network parameters and description of max bytes
  nodes/mainnet.md
Labels: documentation, enhancement

#1340 feat: add note about go version
  developers/node-tutorial.md
  nodes/celestia-node.md
Labels: documentation

#1353 feat: add nitrogen cover page and some copy edits
  developers/nitrogen.md
  public/img/nitrogen-testnet.jpg
Labels: documentation

#1347 feat: add curl guide to node-tutorial.md
  developers/node-tutorial.md
Labels: documentation, enhancement

#1363 feat: add direct links to gov params for `blob.GasPerBlobByte` and `auth.TxSizeCostPerByte`
  developers/submit-data.md
Labels: documentation

#1369 feat: version bump celestia-da to v0.12.9 and op stack version compat with v0.12.9
  developers/optimism-devnet.md
  developers/optimism.md
Labels: documentation

#1372 feat: add audit file for optimism
  .vitepress/config.ts
  public/Celestia_OP_Stack_Audit.pdf
Labels: documentation

#1361 feat: remove arabica-9 from docs
  .vitepress/config.ts
  nodes/arabica-9.md
Labels: documentation

#1381 feat: update op to v1.1.0-OP_op-batcher/v1.4.3-CN_v0.12.4
  developers/optimism-devnet.md
Labels: documentation

#1273 docs: explain slashing mechanism
  .vitepress/config.ts
  nodes/celestia-app-slashing.md
Labels: documentation
