Repository celestiaorg/docs, pull requests merged in 2025-04, with the labels that each got.

#1975 Update indexer field value
  how-to-guides/consensus-node.md
Labels: bug, documentation

#1979 Remove extra section
  how-to-guides/consensus-node.md
Labels: bug

#1984 style: update OG image
  .vitepress/config.ts
  public/Documentation.png
Labels: style

#1990 docs: add audits
  .vitepress/config.ts
  how-to-guides/audits.md
Labels: documentation

#1982 docs: correct misuse of 'validator node' across multiple docs
  how-to-guides/bridge-node.md
  how-to-guides/celestia-app.md
  how-to-guides/celestia-node-troubleshooting.md
  how-to-guides/config-toml.md
  how-to-guides/consensus-node.md
  how-to-guides/full-storage-node.md
  how-to-guides/light-node.md
  how-to-guides/mainnet.md
  how-to-guides/snapshots.md
  tutorials/node-tutorial.md
Labels: documentation
